project:
  type: default
  output-dir: ../_build/slides

format:
  anu_slides-revealjs:
    logo: images/ANU-logo.jpg
    self-contained: false # this can blow up the file size and break publication on github pages
    embed-resources: false
    footer: |
      ANU Course Notes: EMSC 3022
    code-links:
      - text: Open in Binder
        icon: rocket-takeoff
        href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-3022/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd
    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-3022
