project:
  type: book
  output-dir: ../_build/book

book:
  title: "Planetary Sciences (EMSC 3022)"
  author:
    - "Louis Moresi"
  date: "01/07/2025"
  bread-crumbs: True
  chapters:
    - part: "**Geodynamics and Planetary Interiors**"
      chapters:
        - index.qmd
        - Overview.qmd

    # - part: "**Basic Language Skills**"
    #   chapters:
    #     - 1-Basics/Ex1-IntroWebPython.qmd
    #     - 1-Basics/Ex2-Variables.qmd
    #     - 1-Basics/Ex2a-Functions.qmd
    #     - 1-Basics/Ex3-Conditionals.qmd
    #     - 1-Basics/Ex4-Loops.qmd
    #     - 1-Basics/Ex5-ListsEtc.qmd
    #     - 1-Basics/Ex6-MoreLoops.qmd
    #     - 1-Basics/Ex7-Strings.qmd
    #     - 1-Basics/Ex8-ReadWriteFiles.qmd

  navbar:
    search: true
    logo: assets/ANU-logo.jpg
    background: "white"
    foreground: "#C58812" # ANU honey colour

  sidebar:
    # logo: Images/COS-EarthSciences-800.jpg
    logo: assets/AuWorldEQ.jpg
    background: "white"
    # foreground: "#C58812" # ANU honey colour

bibliography: references.bib

execute:
  enabled: false

format:
  live-html:
    theme: [united, "assets/theme.scss"] # united / simplex / flatly
    mainfont: "Jost"
    fontsize: 0.9em
    linestretch: 1.7
    linkcolor: "#C58812"
    number-sections: false
    number-depth: 1
    # filters:
    #   - pyodide

    # code-links:
    #   - text: Open in Binder
    #     icon: rocket-takeoff
    #     href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-getting-going-with-python/HEAD?labpath=WebBook/BinderLandingPage.qmd

    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/EMSC-3022

pyodide:
  packages:
    - micropip
    - netcdf4
    - xarray
    - pydap
    - jinja2
    - ssl
    - owslib

  # pdf:
  #   documentclass: scrreprt